### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'libtesseract500': 

### ISSUE THREAD

**Issue by HappyCappybara** [CptWesley/TesserNet#2]
I've installed all 3 packages. Getting the title error when running the project. Error gets thrown on constructor for Tesseract. Any ideas?
```


private void Ocr()
        {
            var testImagePath = "nwTP2.jpg";


            try
            {
                Image im = Image.FromFile(testImagePath);

                Tesseract tesseract = new Tesseract();
                string result = tesseract.Read(im);

                Console.WriteLine(result.ToString());
            }
            catch (Exception e)
            {
                Trace.TraceError(e.ToString());
                Console.WriteLine("Unexpected Error: " + e.Message);
                Console.WriteLine("Details: ");
                Console.WriteLine(e.ToString());
            }
        }
```

**Comment by CptWesley** [comment]
What operating systems are you using? Windows? 32 bits? 64 bits?

**Comment by HappyCappybara** [comment]
Win10 Home x64
OS build 19043.1288

**Comment by CptWesley** [comment]
Can you check for me if the directory `%TEMP%/tessernet/` (aka `C:\Users\<USERNAME>\AppData\Local\Temp\tessernet`) exists? If so, can you give me an overview of all files and folders in there?

**Comment by HappyCappybara** [comment]
![image](https://user-images.githubusercontent.com/50597898/139096796-477fccdc-f056-4a46-9cd8-d71a64ebb11a.png)

**Comment by CptWesley** [comment]
Can you try deleting those files and try it again? If that doesnt work, could you give the full exception message? I don't really have any other ideas of what might be wrong.

**Comment by HappyCappybara** [comment]
Deleted all. Same results. Here's the exception:

`System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'libtesseract500': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
  Source=TesserNet
  StackTrace:
   at TesserNet.Internal.WindowsTesseractApi.NativeMethods.TessBaseAPIDelete(IntPtr handle)
   at TesserNet.Internal.WindowsTesseractApi.TessBaseAPIDelete(IntPtr handle)
   at TesserNet.Tesseract.Dispose(Boolean disposing)
   at TesserNet.Tesseract.Finalize()`

I cloned the repo to dig a little deeper and it looks like it may have something to do with missing .NET frameworks. The latest I have on my machine is 4.7.2 so I'm getting the following build errors. There are also missing dependencies to FxCop and StyleCop in all the projects.

![image](https://user-images.githubusercontent.com/50597898/139115306-684f5349-f74b-48e1-b7dd-db0b260504d2.png)

**Comment by CptWesley** [comment]
The example projects require newer .NET versions than that, so that might be a reason.

**Comment by HappyCappybara** [comment]
I finally got back around to this. Fix was two part: install .NET 4.8, change Platform target from AnyCPU to x64.

**Comment by Pique7** [comment]
I get the same error message, when I use TesserNet in a 32-bit application running in a 64-bit environment.
I changed https://github.com/CptWesley/TesserNet/blob/d543ec974add609f2a1d97b4adc3ecd38b9d5967/src/TesserNet/Internal/Loader.cs#L35 from 
`  if (Environment.Is64BitOperatingSystem)`   (line 35 in Loader.cs)
to
`  if (Environment.Is64BitProcess)`

The `System.DllNotFoundException` was gone, but then repeatedly `PInvokeStackImbalance` errors occur.
I was able to patch this by adding `CallingConvention = CallingConvention.Cdecl` to the `DllImport` attributes in https://github.com/CptWesley/TesserNet/blob/d543ec974add609f2a1d97b4adc3ecd38b9d5967/src/TesserNet/Internal/WindowsTesseractApi.cs#L56 For example:
`[DllImport(DllPath, CharSet = CharSet.Auto, SetLastError = true, CallingConvention = CallingConvention.Cdecl)]`

For the sake of completeness I also inserted following lines in the `CopyResource()` method in `Loader.cs`:
```
  if (File.Exists(filePath) && entry.Length != new System.IO.FileInfo(filePath).Length)
  {
    File.Delete(filePath);
  }
```
before https://github.com/CptWesley/TesserNet/blob/d543ec974add609f2a1d97b4adc3ecd38b9d5967/src/TesserNet/Internal/Loader.cs#L74 This allow you to switch from x86 to x64 build and vice versa without the need for deleting the old DLL files manually in `%TEMP%\tessernet`.

I am not sure whether there are any other issues left in this context, but my application seems to run without any errors for now.

**Comment by CptWesley** [comment]
Always deleting the file on start-up might cause some issues w.r.t. multiple programs/multiple program instances accessing the same library files at the same time, but it would indeed be great if switching between 32 bit and 64 bit apps worked properly.

**Comment by Pique7** [comment]
> Always deleting the file on start-up ...

In my elementary adaption I check for file size equality before deleting the file:
```... entry.Length != new System.IO.FileInfo(filePath).Length ...```
It is not cannonproof in general, but in this special case it worked.

**Comment by CptWesley** [comment]
@Pique7 I believe the current released version solves your issue with switching between x64 and x86 (and solves some other x86 related issues). My apologies with the long time it took to implement this fix.
